/**
 * MTV: Mutation Transaction Verifier (AIA Integrity Auditor)
 * Verifies the cryptographic consistency and internal integrity of 
 * atomic execution artifacts generated by MCR, C04, FBA, and SEA before 
 * final commitment by AEOR. This provides an independent audit layer.
 */
class AtomicTransactionVerifier {

    /**
     * @param {object} dependencies - Structured dependencies injection.
     * @param {CryptographyService} dependencies.crypto - Service for hashing and signing.
     * @param {ArtifactStorage} dependencies.storage - Persistent storage for transaction artifacts.
     * @param {TelemetryService} dependencies.telemetry - Logging service.
     */
    constructor({ crypto, storage, telemetry }) {
        this.crypto = crypto;
        this.storage = storage;
        this.telemetry = telemetry;
    }

    /**
     * Executes the comprehensive integrity check of the transaction artifacts.
     * Ensures consistency between pre-state commitment, execution trace, and post-execution metrics.
     * 
     * @param {string} deploymentID 
     * @param {object} auditContext - Data structure including hashes/signatures from MCR/FBA/SEA.
     * @returns {Promise<{isVerified: boolean, reason?: string}>}
     */
    async verifyTransactionIntegrity(deploymentID, auditContext) {
        this.telemetry.debug(`MTV: Starting integrity verification for ${deploymentID}.`);
        
        // 1. Retrieve the attested execution trace from storage
        const traceArtifact = await this.storage.retrieveTrace(deploymentID);
        
        if (!traceArtifact || !traceArtifact.traceLog) {
            return { isVerified: false, reason: "Missing critical execution trace artifact." };
        }

        // 2. Re-calculate hash of the C-04 trace log
        const calculatedTraceHash = this.crypto.hashArtifact(traceArtifact.traceLog);

        // We assume the MCR/C04 interface stored the expected hash (e.g., in traceArtifact.expectedHash)
        if (calculatedTraceHash !== auditContext.expectedTraceHash) {
             this.telemetry.error(`MTV Integrity Breach: C04 Execution Trace hash mismatch for ${deploymentID}.`);
             return { isVerified: false, reason: "C04 Execution Trace hash mismatch." };
        }

        // 3. Verify SEA/FBA Audit Data Integrity (ensuring audit metrics are cryptographically attested)
        if (!this.crypto.verifySignature(auditContext.metrics, auditContext.auditSignature)) {
             this.telemetry.error(`MTV Integrity Breach: Audit data signature failed verification for ${deploymentID}.`);
            return { isVerified: false, reason: "SEA/FBA Audit data signature verification failed." };
        }

        this.telemetry.info(`MTV: Transaction integrity verified for ${deploymentID}.`);
        return { isVerified: true };
    }
}

module.exports = AtomicTransactionVerifier;