/**
 * MTV: Mutation Transaction Verifier Kernel (AIA Integrity Auditor)
 * Verifies the cryptographic consistency and internal integrity of 
 * atomic execution artifacts generated by MCR, C04, FBA, and SEA before 
 * final commitment by AEOR. This provides an independent audit layer.
 */
class AtomicTransactionVerifierKernel {

    /**
     * @type {CryptoUtilityInterfaceKernel}
     * @private
     */
    #crypto;

    /**
     * @type {SecureResourceLoaderInterfaceKernel}
     * @private
     */
    #storageLoader;

    /**
     * @type {ILoggerToolKernel} // Assuming ILoggerToolKernel for robust logging/telemetry
     * @private
     */
    #logger;

    /**
     * @type {IIntegrityAuditorToolKernel} // Conceptual interface for the injected auditor
     * @private
     */
    #integrityAuditor; 

    /**
     * @param {object} dependencies - Structured dependencies injection.
     * @param {CryptoUtilityInterfaceKernel} dependencies.crypto - Service for hashing and signing.
     * @param {SecureResourceLoaderInterfaceKernel} dependencies.storageLoader - Secure loader for transaction artifacts.
     * @param {ILoggerToolKernel} dependencies.logger - Logging service (replaces telemetry).
     * @param {IIntegrityAuditorToolKernel} dependencies.integrityAuditor - The abstracted integrity checking plugin.
     */
    constructor(dependencies) {
        this.#setupDependencies(dependencies);
    }

    /**
     * Synchronously sets up and validates required dependencies.
     * @param {object} dependencies
     * @private
     */
    #setupDependencies(dependencies) {
        if (!dependencies.crypto || !dependencies.storageLoader || !dependencies.logger || !dependencies.integrityAuditor) {
            throw new Error("Missing required dependencies for AtomicTransactionVerifierKernel: crypto, storageLoader, logger, integrityAuditor.");
        }
        this.#crypto = dependencies.crypto;
        this.#storageLoader = dependencies.storageLoader;
        this.#logger = dependencies.logger;
        this.#integrityAuditor = dependencies.integrityAuditor;
    }

    /**
     * Executes the comprehensive integrity check of the transaction artifacts.
     * Ensures consistency between pre-state commitment, execution trace, and post-execution metrics.
     * 
     * @param {string} deploymentID 
     * @param {object} auditContext - Data structure including hashes/signatures from MCR/FBA/SEA.
     * @returns {Promise<{isVerified: boolean, reason?: string}>}
     */
    async verifyTransactionIntegrity(deploymentID, auditContext) {
        this.#logger.debug(`MTV: Starting integrity verification for ${deploymentID}.`);
        
        // 1. Retrieve the attested execution trace from storage
        let traceArtifact;
        try {
            // Mapping 'retrieveTrace' to a generic SecureResourceLoader operation, assuming a path structure.
            traceArtifact = await this.#storageLoader.loadResource(`trace-artifact://${deploymentID}`);
        } catch (error) {
             this.#logger.error(`MTV Retrieval Error: Failed to load trace artifact for ${deploymentID}.`, { error });
             return { isVerified: false, reason: "Error accessing critical execution trace artifact." };
        }
        
        if (!traceArtifact || !traceArtifact.traceLog) {
            return { isVerified: false, reason: "Missing critical execution trace artifact." };
        }

        // --- 2. Re-calculate and verify hash of the C-04 trace log using plugin ---
        
        // Passing the bound async hashing function from the Crypto kernel.
        const hashFunction = this.#crypto.hashArtifact.bind(this.#crypto);

        const hashCheckResult = await this.#integrityAuditor.verifyHashConsistency(
            traceArtifact.traceLog,
            auditContext.expectedTraceHash,
            hashFunction
        );

        if (!hashCheckResult.isConsistent) {
             this.#logger.error(`MTV Integrity Breach: C04 Execution Trace hash mismatch for ${deploymentID}. Reason: ${hashCheckResult.reason}`);
             return { isVerified: false, reason: "C04 Execution Trace hash mismatch." };
        }
        
        // --- 3. Verify SEA/FBA Audit Data Integrity (Signature check) using plugin ---

        // Passing the bound async signature verification function from the Crypto kernel.
        const verifyFunction = this.#crypto.verifySignature.bind(this.#crypto);

        const signatureCheckResult = await this.#integrityAuditor.verifySignatureIntegrity(
            auditContext.metrics, 
            auditContext.auditSignature,
            verifyFunction
        );

        if (!signatureCheckResult.isValid) {
             this.#logger.error(`MTV Integrity Breach: Audit data signature failed verification for ${deploymentID}. Reason: ${signatureCheckResult.reason}`);
            return { isVerified: false, reason: "SEA/FBA Audit data signature verification failed." };
        }

        this.#logger.info(`MTV: Transaction integrity verified for ${deploymentID}.`);
        return { isVerified: true };
    }
}

module.exports = AtomicTransactionVerifierKernel;