/**
 * MTV: Mutation Transaction Verifier (AIA Integrity Auditor)
 * Verifies the cryptographic consistency and internal integrity of 
 * atomic execution artifacts generated by MCR, C04, FBA, and SEA before 
 * final commitment by AEOR. This provides an independent audit layer.
 */
class AtomicTransactionVerifier {

    /**
     * @param {object} dependencies - Structured dependencies injection.
     * @param {CryptographyService} dependencies.crypto - Service for hashing and signing.
     * @param {ArtifactStorage} dependencies.storage - Persistent storage for transaction artifacts.
     * @param {TelemetryService} dependencies.telemetry - Logging service.
     * @param {IntegrityAuditor} dependencies.integrityAuditor - The abstracted integrity checking plugin.
     */
    constructor({ crypto, storage, telemetry, integrityAuditor }) {
        this.crypto = crypto;
        this.storage = storage;
        this.telemetry = telemetry;
        // Inject the newly formalized plugin instead of accessing a global PLUGINS object
        this.integrityAuditor = integrityAuditor; 
    }

    /**
     * Executes the comprehensive integrity check of the transaction artifacts.
     * Ensures consistency between pre-state commitment, execution trace, and post-execution metrics.
     * 
     * @param {string} deploymentID 
     * @param {object} auditContext - Data structure including hashes/signatures from MCR/FBA/SEA.
     * @returns {Promise<{isVerified: boolean, reason?: string}>}
     */
    async verifyTransactionIntegrity(deploymentID, auditContext) {
        this.telemetry.debug(`MTV: Starting integrity verification for ${deploymentID}.`);
        
        // 1. Retrieve the attested execution trace from storage
        const traceArtifact = await this.storage.retrieveTrace(deploymentID);
        
        if (!traceArtifact || !traceArtifact.traceLog) {
            return { isVerified: false, reason: "Missing critical execution trace artifact." };
        }

        // --- 2. Re-calculate and verify hash of the C-04 trace log using plugin ---
        
        // Direct call to the plugin method, passing the specific implementation function as a dependency
        const hashCheckResult = this.integrityAuditor.verifyHashConsistency(
            traceArtifact.traceLog,
            auditContext.expectedTraceHash,
            this.crypto.hashArtifact.bind(this.crypto)
        );

        if (!hashCheckResult.isConsistent) {
             this.telemetry.error(`MTV Integrity Breach: C04 Execution Trace hash mismatch for ${deploymentID}. Reason: ${hashCheckResult.reason}`);
             return { isVerified: false, reason: "C04 Execution Trace hash mismatch." };
        }
        
        // --- 3. Verify SEA/FBA Audit Data Integrity (Signature check) using plugin ---

        // Direct call to the plugin method, passing the specific implementation function as a dependency
        const signatureCheckResult = this.integrityAuditor.verifySignatureIntegrity(
            auditContext.metrics, 
            auditContext.auditSignature,
            this.crypto.verifySignature.bind(this.crypto)
        );

        if (!signatureCheckResult.isValid) {
             this.telemetry.error(`MTV Integrity Breach: Audit data signature failed verification for ${deploymentID}. Reason: ${signatureCheckResult.reason}`);
            return { isVerified: false, reason: "SEA/FBA Audit data signature verification failed." };
        }

        this.telemetry.info(`MTV: Transaction integrity verified for ${deploymentID}.`);
        return { isVerified: true };
    }
}

module.exports = AtomicTransactionVerifier;