// Mutation Payload Specification Engine (MPSE)
// Purpose: Enforces rigid structural and type compliance for all mutation payloads 
// before EPDP C (P-01 Trust Adjudication) is initiated. This guarantees a validated 
// operational contract is presented to the trust calculus system.

const { validateSchema } = require('@governance/payloadSchemaValidator');
const { MPSE_SCHEMA_V1 } = require('@config/schemas/mutationPayload.json');
const { PayloadSchemaError } = require('./errors/PayloadSchemaError'); // Refactored import
const Logger = require('@utils/Logger'); // Assume standard utility logger

const SUBSYSTEM_ID = 'MPSE';

class MutationPayloadSpecEngine {
    constructor() {
        this.schema = MPSE_SCHEMA_V1;
        Logger.info(`[${SUBSYSTEM_ID}] Initialized. Awaiting mutation proposals.`);
    }

    /**
     * @param {object} payload - The raw mutation proposal generated by M-02.
     * @returns {object} validatedPayload
     * @throws {PayloadSchemaError} if validation fails.
     */
    enforceSpecification(payload) {
        Logger.debug(`[${SUBSYSTEM_ID}] Attempting specification enforcement on incoming payload...`);
        
        const validationResult = validateSchema(payload, this.schema);

        if (!validationResult.isValid) {
            // Extract cleaner error messages for structured handling
            const errorDetails = validationResult.errors.map(e => e.path ? `${e.path}: ${e.message}` : e.message).join(' | ');
            
            Logger.warn(`[${SUBSYSTEM_ID}] Validation failed. Structural breach identified: ${errorDetails}`);
            
            // Throw custom, catchable error type as specified in JSDoc
            throw new PayloadSchemaError(
                "Structural breach identified in mutation payload. Governance contract violation.", 
                payload, 
                errorDetails
            );
        }

        Logger.verbose(`[${SUBSYSTEM_ID}] Payload structurally compliant. Forwarding to P-01.`);
        return payload;
    }
}

module.exports = new MutationPayloadSpecEngine();
