// Mutation Payload Specification Engine (MPSE)
// Purpose: Enforces rigid structural and type compliance for all mutation payloads 
// before EPDP C (P-01 Trust Adjudication) is initiated. This guarantees a validated 
// operational contract is presented to the trust calculus system.

// --- Dependencies ---
const { validateSchema } = require('@governance/payloadSchemaValidator');
const payloadSchemas = require('@config/schemas/mutationPayload.json'); 
const { PayloadSchemaError } = require('./errors/PayloadSchemaError'); 
const Logger = require('@utils/Logger'); 
const Config = require('@config/ConfigurationLoader'); // [NEW: Centralized Configuration]

const SUBSYSTEM_ID = 'MPSE';
// Retrieve the target schema key from configuration for architectural flexibility.
const DEFAULT_SCHEMA_KEY = Config.get('governance.mpseSchemaVersion', 'MPSE_SCHEMA_V1'); 

class MutationPayloadSpecEngine {
    /**
     * Initializes the MPSE with a specific schema version.
     * @param {string} [schemaKey] - The key corresponding to the required schema version.
     */
    constructor(schemaKey) {
        this.schemaVersion = schemaKey || DEFAULT_SCHEMA_KEY;
        
        const schemaDefinition = payloadSchemas[this.schemaVersion];

        if (!schemaDefinition) {
             // Critical initialization failure check
             throw new Error(`[${SUBSYSTEM_ID}] CRITICAL Initialization failure: Schema '${this.schemaVersion}' missing from definition files.`);
        }
        
        this.schema = schemaDefinition;
        Logger.info(`[${SUBSYSTEM_ID}] Initialized with schema version: ${this.schemaVersion}. Awaiting mutation proposals.`);
    }

    /**
     * Enforces rigid structural specification on the mutation payload.
     * @param {object} payload - The raw mutation proposal generated by M-02.
     * @returns {object} validatedPayload - The input payload, guaranteed compliant.
     * @throws {PayloadSchemaError} if validation fails.
     */
    enforceSpecification(payload) {
        // Enhanced trace logging includes payload characteristics for debugging
        Logger.trace(`[${SUBSYSTEM_ID}] -> ENFORCE: Starting specification check (V${this.schemaVersion}). Payload properties: ${Object.keys(payload).length}.`);
        
        const validationResult = validateSchema(payload, this.schema);

        if (!validationResult.isValid) {
            // High-fidelity error aggregation for precise governance logging
            const detailedErrors = validationResult.errors.map(e => ({
                path: e.path || 'Root',
                message: e.message,
                keyword: e.keyword || 'validation' // Include relevant JSON Schema failure metadata
            }));

            const errorSummary = detailedErrors
                .map(e => `[${e.path}] (${e.keyword}): ${e.message}`)
                .join('; ');
            
            Logger.warn(`[${SUBSYSTEM_ID}] Structural breach detected (V${this.schemaVersion}). Summary: ${errorSummary}`);
            
            // Throw custom error, passing structured data to enable deep analysis by calling systems
            throw new PayloadSchemaError(
                `Mutation Payload failed MPSE V${this.schemaVersion} validation.`,
                payload, 
                errorSummary,
                detailedErrors 
            );
        }

        Logger.verbose(`[${SUBSYSTEM_ID}] Payload structurally compliant (V${this.schemaVersion}). Forwarding to P-01 Trust Adjudication.`);
        return payload;
    }
}

// Export the singleton instance using the default configuration key.
module.exports = new MutationPayloadSpecEngine(DEFAULT_SCHEMA_KEY);