// Mutation Payload Specification Engine (MPSE)
// Purpose: Enforces rigid structural and type compliance for all mutation payloads 
// before EPDP C (P-01 Trust Adjudication) is initiated. This guarantees a validated 
// operational contract is presented to the trust calculus system.

const { validateSchema } = require('@governance/payloadSchemaValidator');
const { MPSE_SCHEMA_V1 } = require('@config/schemas/mutationPayload.json');

class MutationPayloadSpecEngine {
    constructor() {
        this.schema = MPSE_SCHEMA_V1;
    }

    /**
     * @param {object} payload - The raw mutation proposal generated by M-02.
     * @returns {object} validatedPayload
     * @throws {PayloadSchemaError} if validation fails.
     */
    enforceSpecification(payload) {
        console.log("MPSE: Enforcing structural specification on mutation payload...");
        
        const validationResult = validateSchema(payload, this.schema);

        if (!validationResult.isValid) {
            const error = `MPSE Validation Failed: Structural breach identified in mutation payload. Details: ${validationResult.errors.join(', ')}`;
            throw new Error(error);
        }

        // Additional checks ensuring required fields are non-null and correctly typed
        if (!payload.target_path || typeof payload.operation_type !== 'string') {
            throw new Error("MPSE: Critical field validation failure (target/type).");
        }

        console.log("MPSE: Payload is structurally compliant.");
        return payload;
    }
}

module.exports = new MutationPayloadSpecEngine();