// core/Telemetry/GAXEventRegistry.js
/**
 * Standardized Event Names for the GAX Telemetry Service.
 * These constants use a structured "NAMESPACE:SUBDOMAIN:ACTION" format 
 * to ensure consistency, machine readability, and effective filtering 
 * in monitoring and logging systems.
 */
const GAXEventRegistry = Object.freeze({
    // System Lifecycle (SYS)
    SYS_INIT_START: 'SYS:INIT:START',
    SYS_INIT_COMPLETE: 'SYS:INIT:COMPLETE',
    SYS_EXECUTION_START: 'SYS:EXECUTION:START',
    SYS_EXECUTION_END: 'SYS:EXECUTION:END',
    SYS_SHUTDOWN: 'SYS:SHUTDOWN',

    // Policy & Verification (PV)
    PV_REQUEST_INITIATED: 'PV:REQUEST:INITIATED',
    PV_RULE_CHECK_SUCCESS: 'PV:RULE:CHECK:SUCCESS',
    PV_RULE_CHECK_FAILURE: 'PV:RULE:CHECK:FAILURE',

    // Autonomous Evolution (AXIOM)
    AXIOM_GENERATION_START: 'AXIOM:GENERATION:START',
    AXIOM_EVOLUTION_STEP_PERFORMED: 'AXIOM:EVOLUTION:STEP_PERFORMED',
    AXIOM_CODE_COMMITTED: 'AXIOM:CODE:COMMITTED',
    AXIOM_CODE_REVERTED: 'AXIOM:CODE:REVERTED',

    // Planning and Context Management (PLAN)
    PLAN_GOAL_DEFINED: 'PLAN:GOAL:DEFINED',
    PLAN_STEP_GENERATED: 'PLAN:STEP:GENERATED',
    PLAN_CONTEXT_RETRIEVAL_START: 'PLAN:CONTEXT:RETRIEVAL_START',
    PLAN_CONTEXT_RETRIEVAL_COMPLETE: 'PLAN:CONTEXT:RETRIEVAL_COMPLETE',

    // System Diagnostics, Errors, and Warnings (DIAG)
    DIAG_CONFIGURATION_FAULT: 'DIAG:CONFIGURATION:FAULT',
    DIAG_CONTEXT_RESOLUTION_MISSING: 'DIAG:CONTEXT:RESOLUTION_MISSING',
    DIAG_COMPONENT_FATAL_ERROR: 'DIAG:COMPONENT:FATAL_ERROR',
    DIAG_WARNING_THRESHOLD_EXCEEDED: 'DIAG:WARNING:THRESHOLD_EXCEEDED',

    // Telemetry Infrastructure (TEL)
    TEL_PUBLISH_SUCCESS: 'TEL:PUBLISH:SUCCESS',
    TEL_PUBLISH_FAILURE: 'TEL:PUBLISH:FAILURE',
    TEL_DATA_DROPPED: 'TEL:DATA:DROPPED'
});

module.exports = GAXEventRegistry;