const { ConsensusErrorCodes } = require('./ConsensusErrorCodes');

/**
 * Placeholder structure representing the output of the CanonicalErrorSerializer plugin.
 * NOTE: The 'stack' and 'timestamp' properties are generated by the serializer, not the Error instance itself.
 */
interface CanonicalError {
    error: boolean;
    name: string;
    code: string;
    message: string;
    details: object;
    stack?: string[];
    timestamp: string;
}

/**
 * ConsensusError
 * Specialized Error Class for the Sovereign AGI Consensus Stack.
 * Provides standardized, traceable, and categorizable error reporting.
 */
class ConsensusError extends Error {
    public readonly code: string;
    public readonly details: Readonly<object>;

    /**
     * @param {string} code - Machine-readable, unique error code (Must be from ConsensusErrorCodes).
     * @param {string} [message] - Human-readable description of the error (optional).
     * @param {object} [details={}] - Additional structured data for debugging/traceability.
     */
    constructor(code: string, message?: string, details: object = {}) {
        // 1. Guardrail: Enforce known codes and default to E_UNKNOWN if necessary.
        if (!Object.values(ConsensusErrorCodes).includes(code)) {
            code = ConsensusErrorCodes.E_UNKNOWN;
        }

        const finalMessage = message || `Consensus operation failed with code: ${code}.`;

        super(finalMessage);

        this.name = 'ConsensusError';
        this.code = code;
        this.details = Object.freeze(details); // Make details immutable for safety

        // 2. Optimization: Capturing stack trace for V8/Node environments.
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, ConsensusError);
        }
    }

    /**
     * Creates a structured error object for basic serialization (JSON.stringify).
     * For full canonical output (including stack trace processing and timestamp),
     * the external CanonicalErrorSerializer plugin must be used.
     */
    public toJSON(): Omit<CanonicalError, 'stack' | 'timestamp'> {
        // Returns the inherent properties of the error object.
        return {
            error: true,
            name: this.name,
            code: this.code,
            message: this.message,
            details: this.details,
        };
    }

    /**
     * Factory method for cleaner instantiation syntax.
     * @param {string} code 
     * @param {object} [details={}] - Structured data.
     * @param {string} [message] - Optional human message.
     */
    static create(code: string, details: object = {}, message?: string): ConsensusError {
        return new ConsensusError(code, message, details);
    }
}

module.exports = { ConsensusError };