/**
 * Placeholder structure representing the output of the CanonicalErrorSerializer plugin.
 * NOTE: The 'stack' and 'timestamp' properties are generated by the serializer, not the Error instance itself.
 */
interface CanonicalError {
 error: boolean;
 name: string;
 code: string;
 message: string;
 details: object;
 stack?: string[];
 timestamp: string;
}

/**
 * Creates and binds the ConsensusError class to its required immutable configuration.
 * This implementation ensures that configuration constants are injected via Dependency Injection (DI)
 * rather than synchronously loaded via `require`.
 *
 * @param { Readonly < object>} errorCodes - The immutable registry map containing consensus error codes (e.g., E_UNKNOWN).
 * @returns {typeof ConsensusError }
 */
function createConsensusErrorClass(errorCodes: Readonly < object>) {

 const E_UNKNOWN = errorCodes.E_UNKNOWN || 'E_UNKNOWN';
 // Optimize lookup by calculating valid codes once.
 const VALID_CODES = Object.values(errorCodes);

 /**
 * ConsensusError
 * Specialized Error Class for the Sovereign AGI Consensus Stack.
 * Provides standardized, traceable, and categorizable error reporting.
 */
 class ConsensusError extends Error {
 public readonly code: string;
 public readonly details: Readonly < object>;

 /**
 * @param {string} code - Machine-readable, unique error code (Must be from the injected codes).
 * @param {string} [message] - Human-readable description of the error (optional).
 * @param {object} [details={}] - Additional structured data for debugging/traceability.
 */
 constructor(code: string, message?: string, details: object = {}) {
 let effectiveCode = code;

 // 1. Guardrail: Enforce known codes and default to E_UNKNOWN if necessary.
 if (!VALID_CODES.includes(effectiveCode)) {
 effectiveCode = E_UNKNOWN;
 }

 const finalMessage = message || `Consensus operation failed with code: ${effectiveCode}.`;

 super(finalMessage);

 this.name = 'ConsensusError';
 this.code = effectiveCode;
 this.details = Object.freeze(details); // Make details immutable for safety

 // 2. Optimization: Capturing stack trace for V8/Node environments.
 if (Error.captureStackTrace) {
 // Ensure stack trace ignores this constructor
 Error.captureStackTrace(this, ConsensusError);
 }
 }

 /**
 * Creates a structured error object for basic serialization (JSON.stringify).
 * For full canonical output (including stack trace processing and timestamp),
 * the external CanonicalErrorSerializer plugin must be used.
 */
 public toJSON(): Omit < CanonicalError, 'stack' | 'timestamp'> {
 // Returns the inherent properties of the error object.
 return {
 error: true,
 name: this.name,
 code: this.code,
 message: this.message,
 details: this.details,
 };
 }

 /**
 * Factory method for cleaner instantiation syntax.
 * @param {string} code
 * @param {object} [details={}] - Structured data.
 * @param {string} [message] - Optional human message.
 */
 static create(code: string, details: object = {}, message?: string): ConsensusError {
 return new ConsensusError(code, message, details);
 }
 }

 return ConsensusError;
}

module.exports = { createConsensusErrorClass };
