const LOG_LEVELS = {
    DEBUG: 1,
    INFO: 2,
    WARN: 3,
    ERROR: 4,
    SILENT: 5
};

// --- Internal Fallback Processor ---
// Provides the default logging logic if no global Kernel hook (__CANONICAL_LOG_PROCESSOR__) is provided.
const DefaultLogProcessor = {
    /**
     * @param {{context: string, levelName: string, configLevel: number, messageArgs: any[], levelValue: number}} options
     * @returns {{shouldLog: boolean, consoleMethod: string, prefix: string, payload: any[]}}
     */
    execute(options) {
        const { context, levelName, configLevel, messageArgs, levelValue } = options;
        
        const result = { shouldLog: false, consoleMethod: 'log', prefix: '', payload: messageArgs };

        // 1. Filtering check
        if (levelValue >= configLevel) {
            result.shouldLog = true;
            
            // 2. Formatting
            const timestamp = new Date().toISOString();
            result.prefix = `[${timestamp}] [${levelName}] [${context}]`;
            
            // 3. Output method determination
            result.consoleMethod = levelName.toLowerCase();
        }
        
        return result;
    }
};

/**
 * Standardized Logger utility for engine components.
 * Delegates log formatting and filtering logic to the CanonicalLogProcessorTool plugin if available.
 */
class Logger {
    /** @type {number} */
    #level;
    /** @type {string} */
    #context;

    /**
     * @param {string} context - Identifier for the module or area generating the log (e.g., 'ResolutionStrategyLoader').
     * @param {number} [level=LOG_LEVELS.INFO] - The minimum level to output.
     */
    constructor(context, level = LOG_LEVELS.INFO) {
        this.#context = context;
        this.#level = level;
    }
    
    /**
     * Internal method to process and output logs via the active processor.
     * @param {string} levelName 
     * @param {number} levelValue 
     * @param {...any} args 
     */
    _output(levelName, levelValue, ...args) {
        
        // Use the global Canonical Log Processor if injected, otherwise use the internal default.
        const processor = (typeof __CANONICAL_LOG_PROCESSOR__ !== 'undefined' && typeof __CANONICAL_LOG_PROCESSOR__.execute === 'function')
            ? __CANONICAL_LOG_PROCESSOR__
            : DefaultLogProcessor;
        
        // Process log data using the selected processor
        const result = processor.execute({
            context: this.#context,
            levelName: levelName,
            configLevel: this.#level,
            messageArgs: args,
            levelValue: levelValue
        });

        if (result.shouldLog) {
            // Safely retrieve the console method determined by the plugin
            const consoleMethod = console[result.consoleMethod] || console.log;
            
            // Output the prefix and payload generated by the processor
            if (result.prefix) {
                consoleMethod(result.prefix, ...result.payload);
            } else {
                consoleMethod(...result.payload);
            }
        }
    }

    debug(...args) {
        this._output('DEBUG', LOG_LEVELS.DEBUG, ...args);
    }

    info(...args) {
        this._output('INFO', LOG_LEVELS.INFO, ...args);
    }

    warn(...args) {
        this._output('WARN', LOG_LEVELS.WARN, ...args);
    }

    error(...args) {
        this._output('ERROR', LOG_LEVELS.ERROR, ...args);
    }
}

Logger.Levels = LOG_LEVELS;
export default Logger;