const LOG_LEVELS = {
    DEBUG: 1,
    INFO: 2,
    WARN: 3,
    ERROR: 4,
    SILENT: 5
};

/**
 * Standardized Logger utility for engine components.
 * Delegates log formatting and filtering logic to the CanonicalLogProcessorTool plugin.
 */
class Logger {
    /** @type {number} */
    #level;
    /** @type {string} */
    #context;

    /**
     * @param {string} context - Identifier for the module or area generating the log (e.g., 'ResolutionStrategyLoader').
     * @param {number} [level=LOG_LEVELS.INFO] - The minimum level to output.
     */
    constructor(context, level = LOG_LEVELS.INFO) {
        this.#context = context;
        this.#level = level;
    }
    
    /**
     * Internal method to process and output logs via the CanonicalLogProcessorTool.
     * @param {string} levelName 
     * @param {number} levelValue 
     * @param {...any} args 
     */
    _output(levelName, levelValue, ...args) {
        
        // Delegation to CanonicalLogProcessorTool Plugin (simulated call)
        if (typeof __CANONICAL_LOG_PROCESSOR__ !== 'undefined' && typeof __CANONICAL_LOG_PROCESSOR__.execute === 'function') {
            const result = __CANONICAL_LOG_PROCESSOR__.execute({
                context: this.#context,
                levelName: levelName,
                configLevel: this.#level,
                messageArgs: args,
                levelValue: levelValue
            });

            if (result.shouldLog) {
                // Safely retrieve the console method determined by the plugin
                const consoleMethod = console[result.consoleMethod] || console.log;
                // Output the prefix and payload generated by the plugin
                consoleMethod(result.prefix, ...result.payload);
            }
        } else {
            // Fallback/Original logic if tool is not present
             if (levelValue >= this.#level) {
                const timestamp = new Date().toISOString();
                const prefix = `[${timestamp}] [${levelName}] [${this.#context}]`;
                const consoleMethod = console[levelName.toLowerCase()] || console.log;
                consoleMethod(prefix, ...args);
            }
        }
    }

    debug(...args) {
        this._output('DEBUG', LOG_LEVELS.DEBUG, ...args);
    }

    info(...args) {
        this._output('INFO', LOG_LEVELS.INFO, ...args);
    }

    warn(...args) {
        this._output('WARN', LOG_LEVELS.WARN, ...args);
    }

    error(...args) {
        this._output('ERROR', LOG_LEVELS.ERROR, ...args);
    }
}

Logger.Levels = LOG_LEVELS;
export default Logger;