import { PolicyIntegrityError } from '../errors/policyErrors.js';
import { JsonSchemaValidator } from '../utils/JsonSchemaValidator.js';
// Import definitions/constants
import { 
    MINIMAL_FALLBACK_SCHEMA, 
    DEFAULT_GOVERNANCE_SCHEMA_PATH,
    AJV_CONFIGURATION
} from './schema/PolicySchemaDefinitions.js';

class PolicySchemaValidator {
    /**
     * @type {JsonSchemaValidator}
     */
    #validator;

    /**
     * Initializes the validator by compiling the policy governance schema.
     * @param {string} schemaPath - Optional path to the external JSON schema file.
     */
    constructor(schemaPath = DEFAULT_GOVERNANCE_SCHEMA_PATH) {
        try {
            // Initialize the generic validator using policy-specific constants
            this.#validator = new JsonSchemaValidator(
                schemaPath,
                AJV_CONFIGURATION,
                MINIMAL_FALLBACK_SCHEMA
            );
        } catch (e) {
            // Indicate structural invalidity of the JSON schema itself
            console.error(`[CSV-01] AJV Compilation Failure: Schema in ${schemaPath || 'Fallback'} is invalid.`, e.message);
            // Re-throw the error generated by the underlying utility
            throw new Error(`Failed to compile governance schema: ${e.message}`);
        }
    }

    /**
     * Validates the provided policy configuration data against the governance schema.
     * @param {object} policyConfigData - The configuration object (e.g., from the Policy Engine, C-15).
     * @returns {true} If validation passes.
     * @throws {PolicyIntegrityError} If validation fails.
     */
    validate(policyConfigData) {
        // The internal validator handles initial sanity checks and returns raw AJV errors.
        const { isValid, errors } = this.#validator.validate(policyConfigData);
        
        if (!isValid) {
            const errorList = errors || [];
            
            // Generate robust error details utilizing AJV fields
            const errorDetails = errorList.map(e => {
                const dataPath = e.instancePath || e.dataPath || 'root';
                const schemaPath = e.schemaPath || 'unknown';
                return `[Path: ${dataPath}] ${e.message}. Schema Ref: ${schemaPath} (Keyword: ${e.keyword})`;
            }).join('\n');
            
            console.error(`[CSV-01] Policy Validation Failed against schema ${this.#validator.schemaSourceIdentifier}. Errors: ${errorList.length}. Details:\n${errorDetails}`);

            throw new PolicyIntegrityError(
                `Policy configuration failed strict compliance schema validation. Found ${errorList.length} structural issues.`, 
                errorList 
            );
        }
        return true;
    }
}

export default PolicySchemaValidator;