# system/utility/deep_patch_utility.py: State Differential Application Utility

from typing import Dict, Any, List, Union
from jsonpointer import resolve_pointer, set_pointer, delete_pointer
from copy import deepcopy

# Re-use types from deep_diff_utility
JsonValue = Union[str, int, float, bool, None, Dict[str, Any], List[Any]]
State = Dict[str, Any] 
JsonPatchOperation = Dict[str, Any] 
Differential = List[JsonPatchOperation] 

def apply_patch(target_state: State, patch: Differential) -> State:
    """
    Applies a JSON Patch (RFC 6902) list of operations to a target state.

    Note: The state is deepcopied before patching to ensure immutability of the caller's reference.
    
    Args:
        target_state: The dictionary or list to be modified.
        patch: A list of JSON Patch operations.

    Returns:
        The patched state.
    Raises:
        KeyError, IndexError, or ValueError on invalid operations or pointers.
    """
    # Create a deep copy to ensure the original state is not modified in place
    state = deepcopy(target_state)
    
    # Ensure we are applying patches relative to the root '/' for internal processing
    
    for op in patch:
        op_type = op['op']
        path = op['path']

        if path and path[0] == '/':
            # jsonpointer library expects paths without the leading '/'
            pointer = path[1:]
        elif path == '':
            # Handle root replacement if necessary, though diff utility should avoid this for objects/lists.
            # We primarily assume state is a dict/list for standard diffing.
            raise ValueError("Cannot apply patch to root path using this utility.")
        else:
             # Path is malformed or empty string (should be '/')
             pointer = path

        try:
            if op_type == 'add' or op_type == 'replace':
                value = op['value']
                # Use set_pointer for both add (to new index) and replace (to existing index)
                set_pointer(state, pointer, value, inplace=True)

            elif op_type == 'remove':
                # Delete pointer operation
                delete_pointer(state, pointer, inplace=True)

            elif op_type == 'test':
                expected_value = op['value']
                actual_value = resolve_pointer(state, pointer)
                if actual_value != expected_value:
                    raise ValueError(f"JSON Patch Test failed at {path}. Expected {expected_value}, got {actual_value}.")

            elif op_type == 'move' or op_type == 'copy':
                 # NOTE: Move/Copy are not generated by deep_diff_utility, but included for standard compliance
                raise NotImplementedError(f"Operation '{op_type}' not supported in core state patching.")

            else:
                raise ValueError(f"Unsupported JSON Patch operation: {op_type}")

        except Exception as e:
            raise RuntimeError(f"Failed to apply JSON Patch operation {op}: {e}")

    return state

# For integration:
# if __name__ == '__main__':
#     from deep_diff_utility import calculate_deep_diff
#     old = {'a': 1, 'b': [1, 2, 3]}
#     new = {'a': 5, 'b': [1, 4]}
#     diff = calculate_deep_diff(old, new)
#     print(f"Diff: {diff}")
#     patched = apply_patch(old, diff)
#     print(f"Patched: {patched}")
#     assert patched == new
