# system/utility/patch_utility.py: State Patch Application Utility

from typing import Any, List, Dict
from jsonpatch import apply_patch, JsonPatchException

Differential = List[Dict[str, Any]]
State = Dict[str, Any]

# NOTE: This implementation relies on the 'jsonpatch' external library
# If external dependencies are restricted, a custom, path-based patch applicator must be implemented here.

def apply_differential(state: State, differential: Differential) -> State:
    """
    Applies a JSON Patch differential (Delta Psi) to a given state structure.
    
    Args:
        state: The target dictionary/state to be modified.
        differential: The JSON Patch list generated by calculate_deep_diff.
        
    Returns:
        The patched (new) state.
    """
    try:
        # Ensure we operate on a copy if the underlying state needs immutability enforcement
        return apply_patch(state, differential, in_place=False)
    except JsonPatchException as e:
        # Robust error handling crucial for AGI state recovery
        raise RuntimeError(f"Failed to apply state differential: {e}")

def revert_differential(state: State, differential: Differential) -> State:
    """
    Calculates and applies the inverse patch to the state to achieve rollback.
    This requires deep diff calculations that store 'from' data.
    
    NOTE: Full rollback requires a more complex utility that generates the inverse patch.
    For simplicity, relying on re-applying an inverse diff calculation is usually necessary.
    This placeholder serves as a reminder for necessary rollback logic.
    """
    raise NotImplementedError("Inverse patch generation and rollback implementation required.")