// src/governance/schemas/M01PolicySchema.js

/**
 * A94 Governance Schema Definition: M-01 Refinement Proposal Input Structure.
 * Defines the required contract for data flowing from the GMRE (Refinement Engine)
 * into the DCG (Constraint Generator), ensuring strict data integrity before mutation.
 *
 * NOTE: This file assumes the DCG utilizes a concrete validation library (like Joi or Zod) 
 * to enforce these definitions in runtime.
 */

export const PlaceholderJoi = {
    string: () => PlaceholderJoi,
    number: () => PlaceholderJoi,
    object: (schema) => schema ? schema : PlaceholderJoi, 
    array: () => PlaceholderJoi, 
    items: () => PlaceholderJoi,
    required: () => PlaceholderJoi,
    optional: () => PlaceholderJoi,
    precision: () => PlaceholderJoi,
    valid: () => PlaceholderJoi,
    description: () => PlaceholderJoi
};

export const PolicyRuleSchema = PlaceholderJoi.object({
    ruleId: PlaceholderJoi.string().required().description('Unique identifier for the proposed rule.'),
    ruleType: PlaceholderJoi.string().valid('VETO', 'WEIGHT', 'LIMIT').required(),
    parameters: PlaceholderJoi.object().required().description('Specific parameters defining the rule activation/value.'),
    justificationMetric: PlaceholderJoi.string().required().description('Metric ID from GMRE audit data justifying this rule.')
});

export const RefinementProposalSchema = PlaceholderJoi.object({
    proposalId: PlaceholderJoi.string().required().description('Unique ID generated by the GMRE for this cycle.'),
    optimalS02Adjustment: PlaceholderJoi.number().optional().precision(4).description('Proposed delta for Risk Floor adjustment (S-02 parameter).'),
    recommendedVetoRules: PlaceholderJoi.array().items(PolicyRuleSchema).optional().description('Proposed additions to S-03 hard stop veto rules.'),
    auditCycle: PlaceholderJoi.string().required().description('The audit cycle that triggered this proposal.'),
});
