// src/governance/schemas/M01PolicySchema.js

/**
 * A94 Governance Schema Definition: M-01 Refinement Proposal Input Structure (Descriptive Format).
 * Defines the required contract for data flowing from the GMRE (Refinement Engine)
 * into the DCG (Constraint Generator), ensuring strict data integrity before mutation.
 *
 * RATIONALE: The underlying Schema factory logic has been extracted into the
 * DescriptiveSchemaFactory plugin to promote reuse, consistency, and separation of concerns.
 */

// CRITICAL: The Schema utility object is now provided by the DescriptiveSchemaFactory plugin.
// Assuming dependency injection makes the utility accessible here.
// Example simulation of dependency access (actual mechanism depends on runtime environment):
const Schema = DescriptiveSchemaFactory.execute(); 

// --- Sub-Schemas ---

/**
 * Defines the structure for a single, proposed governance rule change.
 */
const PolicyRuleSchema = Schema.object({
    ruleId: Schema.required(Schema.string('Unique identifier for the proposed rule.')),
    ruleType: Schema.required(Schema.valid(
        Schema.string(),
        ['VETO', 'WEIGHT', 'LIMIT'] // Enforcement types recognized by the Constraint Generator
    )),
    parameters: Schema.required(Schema.object({}).description('Specific parameters defining the rule activation/value.')),
    justificationMetric: Schema.required(Schema.string('Metric ID from GMRE audit data justifying this rule.'))
});

/**
 * Defines the entire M01 Refinement Proposal payload from the GMRE.
 */
const RefinementProposalSchema = Schema.object({
    proposalId: Schema.required(Schema.string('Unique ID generated by the GMRE for this cycle.')),
    schemaVersion: Schema.required(Schema.valid(Schema.string('Schema contract version'), ['M01.v1'])),
    optimalS02Adjustment: Schema.optional(Schema.precision(
        Schema.number('Proposed delta for Risk Floor adjustment (S-02 parameter).'),
        4
    )),
    recommendedPolicyRules: Schema.optional(
        Schema.array(PolicyRuleSchema)
        .description('Proposed additions or modifications to policy rules (VETO, WEIGHT, LIMIT).')
    ),
    auditCycle: Schema.required(Schema.string('The unique identifier for the audit cycle that triggered this proposal.')),
});

module.exports = {
    PolicyRuleSchema,
    RefinementProposalSchema
};
