/**
 * Cryptography.js
 * ----------------------------------------------------
 * Core utility for secure cryptographic operations, supporting hashing
 * of canonical data structures generated by CanonicalJson for integrity verification.
 */

import { createHash } from 'crypto';
import CanonicalJson from './CanonicalJson';

export class Cryptography {

  /**
   * Generates a deterministic SHA-256 hash of an object by first converting
   * it into a canonical JSON string.
   * @param {Object} data - The object to hash.
   * @param {string} [encoding='hex'] - Output encoding (e.g., 'hex', 'base64').
   * @returns {string} The cryptographic hash.
   */
  static hashCanonical(data, encoding = 'hex') {
    // 1. Convert the data to its canonical string representation.
    const canonicalString = CanonicalJson.stringify(data);

    // 2. Compute the hash using the standard secure algorithm (SHA-256).
    const hash = createHash('sha256');
    hash.update(canonicalString, 'utf8');
    
    return hash.digest(encoding);
  }

  // Future methods: signature verification, encryption utilities, key management.
}

export default Cryptography;
