/**
 * Cryptography.js
 * ----------------------------------------------------
 * Core utility for secure cryptographic operations, supporting hashing
 * of canonical data structures generated by CanonicalJson for integrity verification.
 */

import CanonicalJson from './CanonicalJson';
import { CanonicalHashingTool } from '../plugins/CanonicalHashingTool';

export class Cryptography {

  /**
   * Generates a deterministic SHA-256 hash of an object by first converting
   * it into a canonical JSON string.
   * @param {Object} data - The object to hash.
   * @param {string} [encoding='hex'] - Output encoding (e.g., 'hex', 'base64').
   * @returns {string} The cryptographic hash.
   */
  static hashCanonical(data: object, encoding: string = 'hex'): string {
    // Delegate the combined canonicalization and hashing logic to the specialized tool via proxy.
    return Cryptography.#delegateToHashingTool(data, encoding);
  }

  /**
   * Private static I/O proxy to delegate execution to the external CanonicalHashingTool.
   * This isolates the direct interaction with the external dependency, enforcing architectural separation.
   */
  static #delegateToHashingTool(data: object, encoding: string): string {
    // Delegate execution to the specialized tool, passing the required dependency (CanonicalJson.stringify)
    return CanonicalHashingTool.execute({
      data: data,
      encoding: encoding,
      canonicalizer: CanonicalJson.stringify
    });
  }

  // Future methods: signature verification, encryption utilities, key management.
}

export default Cryptography;