/**
 * DeepNormalizer Utility
 * Provides methods for creating stable, canonical representations of JavaScript objects,
 * ensuring deterministic serialization regardless of key insertion order.
 * Essential for cryptographic hashing (fingerprinting) and reliable comparison.
 */

// --- Conceptual Plugin Access Layer ---
// Assumes the plugin 'CanonicalObjectNormalizer' is accessible via a service locator or injection.
declare const PluginAccess: {
    CanonicalObjectNormalizer: {
        normalize: (args: { data: any }) => any;
    };
};

class DeepNormalizer {

    /**
     * Recursively sorts the keys of an object or array of objects using the CanonicalObjectNormalizer plugin.
     * @param {any} obj 
     * @returns {any} Normalized object/array
     */
    static deepSortKeys(obj: any): any {
        // Delegate key sorting (canonical normalization) to the dedicated tool
        // This ensures the logic is centralized and testable.
        return PluginAccess.CanonicalObjectNormalizer.normalize({ data: obj });
    }

    /**
     * Generates a stable JSON string representation of an object.
     * This is suitable for hashing or canonical comparison.
     * @param {object} obj - The object to stringify.
     * @returns {string} Canonical JSON string.
     */
    static stableStringify(obj: object): string {
        // Use the canonical representation generated by the tool before stringification
        const normalized = DeepNormalizer.deepSortKeys(obj);
        return JSON.stringify(normalized);
    }
}

module.exports = DeepNormalizer;