// src/config/DialAnalysisConfigValidatorKernel.js

/**
 * Kernel responsible for loading, validating, and normalizing the Dial Analysis Configuration Map.
 * It enforces architectural separation by using Dependency Injection for structural validation checks.
 */
class DialAnalysisConfigValidatorKernel {

    #specValidator;

    /**
     * Defines the high-level structural schema for Dial Analysis Configuration.
     * NOTE: This constant is defined internally but must eventually be moved to a Compliance/Schema Registry Kernel
     * to fully satisfy the goal of removing raw configuration constants from logic components.
     */
    #DIAL_ANALYSIS_SCHEMA = [
        { key: 'metrics_config', type: 'object', required: true },
        { key: 'precondition_definitions', type: 'object', required: true },
        { key: 'response_rules', type: 'array', required: true }
    ];

    /**
     * @param {ISpecValidatorKernel} specValidator Kernel provided for structural schema checking.
     */
    constructor(specValidator) {
        this.#specValidator = specValidator;
        this.#setupDependencies();
    }

    /**
     * Extracts synchronous dependency validation and initialization logic.
     * @private
     */
    #setupDependencies() {
        // Note: Assumes ISpecValidatorKernel is the dependency interface based on strategic ledger.
        if (!this.#specValidator || typeof this.#specValidator.validate !== 'function') {
            throw new Error('Dependency ISpecValidatorKernel must be provided and implement a validate method.');
        }
    }

    /**
     * I/O Proxy method for delegating structural validation to the injected kernel.
     * @param {Object} rawConfig 
     * @private
     */
    #delegateToSpecValidatorValidate(rawConfig) {
        try {
            // Pass the data and the specific schema definition to the structural validator.
            this.#specValidator.validate(rawConfig, this.#DIAL_ANALYSIS_SCHEMA);
        } catch (e) {
            // Re-throw specific errors generated by the structural validator, wrapped for context
            throw new Error(`Dial Analysis Configuration structural error: ${e.message}`);
        }
    }

    /**
     * Validates and returns a standardized configuration object.
     * @param {Object} rawConfig The raw JSON configuration object (e.g., dial_analysis_map.json).
     * @returns {Object} The validated and normalized configuration.
     * @throws {Error} If the configuration fails validation checks.
     */
    validateConfig(rawConfig) {
        
        // 1. Basic Existence Check
        if (!rawConfig || typeof rawConfig !== 'object') {
            throw new Error("Configuration map is null, undefined, or not an object.");
        }
        
        // 2. Structural Check (Delegated via I/O Proxy)
        this.#delegateToSpecValidatorValidate(rawConfig);

        const config = rawConfig; // Now guaranteed to have basic structure

        // 3. Metric and Precondition Consistency Check (Domain-specific validation)
        for (const [pKey, definition] of Object.entries(config.precondition_definitions)) {
            if (!definition || typeof definition !== 'object') {
                throw new Error(`Precondition definition for ${pKey} is invalid.`);
            }
            if (!definition.check || typeof definition.check !== 'string') {
                 throw new Error(`Precondition ${pKey} is missing a 'check' field defining the metric or 'check' is not a string.`);
            }
            const targetMetricKey = definition.check;
            
            if (!config.metrics_config[targetMetricKey]) {
                throw new Error(`Metric configuration missing for precondition target: ${targetMetricKey} referenced by precondition ${pKey}`);
            }
        }

        // 4. Rule Structure Normalization
        config.response_rules = config.response_rules.map(rule => {
            if (typeof rule !== 'object' || rule === null) {
                throw new Error("Response rule entry is invalid or null.");
            }
            return {
                ...rule,
                // Ensure every rule has a defined priority, defaulting to 0
                priority: rule.priority || 0
            };
        });

        return config;
    }
}

export default DialAnalysisConfigValidatorKernel;