/// Configuration structure for initializing the TeeKeyManager.
/// Decouples platform-specific constants and endpoints from the core manager trait implementation.

#[derive(Debug, Clone)]
pub struct TeeKeyConfig {
    /// Specifies the target TEE platform (e.g., "SGX", "AMD_SEV", "IFK_MOCK").
    pub platform_id: String,
    /// The required length for cryptographic signatures generated by this TEE.
    pub signature_length: usize,
    /// Endpoint or local path for interfacing with the Platform Attestation Service (PAS).
    pub pas_endpoint: Option<String>,
    /// Security level required for initial provisioning (0=lowest, 3=highest).
    pub required_security_level: u8,
}

impl Default for TeeKeyConfig {
    fn default() -> Self {
        TeeKeyConfig {
            platform_id: "IFK_MOCK".to_string(),
            signature_length: 64,
            pas_endpoint: None,
            required_security_level: 1,
        }
    }
}
