// src/utils/schema/SchemaAdapter.js

import { SchemaTransformationAdapter } from '@plugin/SchemaTransformationAdapter';

// Define the structure of the internal descriptive schema contract (A94 format)
interface A94FieldDefinition {
    type: 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object' | 'enum';
    required?: boolean;
    optional?: boolean;
    default?: any;
    description?: string;
    options?: (string | number)[]; // For enum
    items?: A94FieldDefinition; // For array
    schema?: A94SchemaFields; // For object
}

interface A94SchemaFields {
    [key: string]: A94FieldDefinition;
}

interface A94DescriptiveSchema {
    type: 'object';
    schema: A94SchemaFields;
}

// Define the Internal Representation (IR) generated by the plugin
interface SchemaIR {
    zType: string;
    modifiers: string[];
    args: any[];
    meta: {
        description?: string;
        defaultValue?: any;
        nestedSchema?: { [key: string]: SchemaIR };
    };
}

// --- Zod Setup ---

const ZodPlaceholder: any = {
    // Basic types and chains
    string: () => ZodPlaceholder,
    number: () => ZodPlaceholder,
    boolean: () => ZodPlaceholder,
    object: (shape?: any) => ZodPlaceholder,
    array: (itemSchema?: any) => ZodPlaceholder,
    enum: (options: any[]) => ZodPlaceholder,
    
    // Modifiers/Methods
    optional: () => ZodPlaceholder,
    required: () => ZodPlaceholder,
    refine: () => ZodPlaceholder,
    describe: (d: string) => ZodPlaceholder,
    default: (d: any) => ZodPlaceholder,
    
    // Execution
    parse: (data: any) => { 
        console.warn('Zod placeholder parsing data. If this warning appears in production, Zod is likely missing.'); 
        return data || {}; 
    }, 
};

// NOTE: Assumes Zod is the target validation library. Uses ZodPlaceholder if not imported.
const z: any = ZodPlaceholder;


/**
 * Recursively converts the Schema IR into a concrete Zod schema definition structure.
 * This function uses the IR generated by the SchemaTransformationAdapter plugin.
 * @param {SchemaIR} ir - The Internal Representation of a field.
 * @returns {any} A Zod schema object or definition map.
 */
function buildZodDefinition(ir: SchemaIR): any {
    let zodType: any;

    // 1. Determine the base type
    switch (ir.zType) {
        case 'string':
            zodType = z.string();
            break;
        case 'number':
            zodType = z.number();
            break;
        case 'boolean':
            zodType = z.boolean();
            break;
        case 'enum':
            // ir.args[0] should be the array of options
            if (ir.args.length > 0) {
                 zodType = z.enum(ir.args[0]);
            } else {
                 zodType = z.string(); // Fallback
            }
            break;
        case 'array':
            // ir.args[0] should be the IR of the items
            if (ir.args.length > 0 && ir.args[0].zType) {
                const itemIR = ir.args[0] as SchemaIR;
                zodType = z.array(buildZodDefinition(itemIR));
            } else {
                zodType = z.array(z.unknown());
            }
            break;
        case 'object':
            if (ir.meta.nestedSchema) {
                const nestedShape: { [key: string]: any } = {};
                for (const key in ir.meta.nestedSchema) {
                    nestedShape[key] = buildZodDefinition(ir.meta.nestedSchema[key]);
                }
                zodType = z.object(nestedShape);
            } else {
                zodType = z.object({});
            }
            break;
        default:
            console.warn(`Unknown type encountered in SchemaAdapter IR: ${ir.zType}`);
            zodType = z.unknown();
    }

    // 2. Apply modifiers and metadata
    if (ir.meta.description) {
        zodType = zodType.describe(ir.meta.description);
    }
    
    if (ir.modifiers.includes('default') && ir.meta.defaultValue !== undefined) {
        zodType = zodType.default(ir.meta.defaultValue);
    }

    if (ir.modifiers.includes('optional')) {
        zodType = zodType.optional();
    }

    return zodType;
}


/**
 * A94 Utility Component: Schema Adapter
 * This utility bridges the library-agnostic Schema definition format 
 * (used in governance/schemas/M01PolicySchema.js) with the concrete
 * runtime validation library (e.g., Zod) used by the system.
 */

/**
 * Transforms the internal descriptive A94 schema contract into a concrete Zod validation object.
 * 
 * @param {A94DescriptiveSchema} descriptiveSchema - The schema object defined using the A94 contract format.
 * @returns {any} A runnable Zod schema object.
 */
export function adaptSchema(descriptiveSchema: A94DescriptiveSchema): any {
    if (typeof descriptiveSchema !== 'object' || descriptiveSchema.type !== 'object') {
        console.error("Invalid base schema structure provided to adapter.");
        return z.object({});
    }

    // 1. Transform the descriptive schema into a standard Internal Representation (IR) using the plugin.
    const irSchemaMap: { [key: string]: SchemaIR } = SchemaTransformationAdapter.execute({ descriptiveSchema });

    // Handle transformation failure
    if (irSchemaMap && (irSchemaMap as any).error) {
        console.error("Schema transformation failed:", (irSchemaMap as any).error);
        return z.object({});
    }

    // 2. Convert the IR into the concrete Zod definition structure recursively.
    const zodShape: { [key: string]: any } = {};
    for (const key in irSchemaMap) {
        if (Object.prototype.hasOwnProperty.call(irSchemaMap, key)) {
            zodShape[key] = buildZodDefinition(irSchemaMap[key]);
        }
    }

    // 3. Create the final Zod object
    return z.object(zodShape);
}