/**
 * @module DashboardStreamer
 * @description Manages continuous polling and streaming of runtime reports generated by RuntimeDashboard.
 * Uses an internal buffer and a basic observer pattern to allow components (e.g., UI, persistent logging) 
 * to subscribe to real-time metric updates without direct polling.
 */

import { generateRuntimeReport } from './runtimeDashboard';

const POLL_INTERVAL_MS = 2500; // Update every 2.5 seconds
let intervalHandle = null;
const subscribers = new Set();
let latestReport = {};

/**
 * Starts the continuous polling process.
 */
export function startDashboardStream() {
    if (intervalHandle) {
        console.warn('Dashboard stream is already active.');
        return;
    }

    console.log(`Starting dashboard stream (Interval: ${POLL_INTERVAL_MS}ms)`);

    const poll = async () => {
        try {
            latestReport = await generateRuntimeReport();
            notifySubscribers(latestReport);
        } catch (error) {
            console.error("Error during runtime report generation:", error);
            // Continue polling, but log the failure
        }
    };

    // Initial run immediately
    poll();

    intervalHandle = setInterval(poll, POLL_INTERVAL_MS);
}

/**
 * Stops the continuous polling process.
 */
export function stopDashboardStream() {
    if (intervalHandle) {
        clearInterval(intervalHandle);
        intervalHandle = null;
        console.log('Dashboard stream stopped.');
    }
}

/**
 * Subscribes a listener function to receive updates.
 * @param {Function} callback Function that accepts the report object as an argument.
 */
export function subscribeToReports(callback) {
    subscribers.add(callback);
    // Immediately provide the latest snapshot upon subscription
    callback(latestReport);
}

/**
 * Unsubscribes a listener function.
 * @param {Function} callback The function to remove.
 */
export function unsubscribeFromReports(callback) {
    subscribers.delete(callback);
}

/**
 * Notifies all subscribed listeners with the new report.
 * @param {Object} report The latest runtime report.
 */
function notifySubscribers(report) {
    for (const subscriber of subscribers) {
        try {
            subscriber(report);
        } catch (e) {
            console.error('Subscriber failed to handle report notification:', e);
        }
    }
}
